namespace Util.Platform.Identity.Data.Seeds;

/// <summary>
/// 资源数据种子
/// </summary>
public static class ResourceSeed {
    /// <summary>
    /// 创建默认资源
    /// </summary>
    public static IEnumerable<Resource> CreateDefaultResources() {
        return new[] {
            new Resource( SeedConst.SystemResourceId,$"{SeedConst.SystemResourceId},",1 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "系统管理",
                I18n = "menu.system",
                PinYin = "xtgl",
                Type = ResourceType.Module,
                SortId = 1,
                Enabled = true,
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "e738a96e-517e-480b-9fb7-5d2616888f1d"u8.ToArray()
            },
            new Resource( SeedConst.AppliationResourceId,$"{SeedConst.SystemResourceId},{SeedConst.AppliationResourceId},",2 ) {
                ApplicationId = SeedConst.ApplicationId,
                ParentId = SeedConst.SystemResourceId,
                Name = "应用程序",
                I18n = "identity.application",
                Icon = "laptop",
                PinYin = "yycx",
                Uri = "/identity/application",
                Type = ResourceType.Module,
                SortId = 1,
                Enabled = true,
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "7664ee42-1968-4b6a-93e6-851524eaa97c"u8.ToArray()
            },
            new Resource( SeedConst.ClaimResourceId,$"{SeedConst.SystemResourceId},{SeedConst.ClaimResourceId},",2 ) {
                ApplicationId = SeedConst.ApplicationId,
                ParentId = SeedConst.SystemResourceId,
                Name = "声明",
                I18n = "identity.claim",
                Icon = "idcard",
                PinYin = "sm",
                Uri = "/identity/claim",
                Type = ResourceType.Module,
                SortId = 2,
                Enabled = true,
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "44fd1a4e-49ab-4a5c-b7ec-f760ffaa37ba"u8.ToArray()
            },
            new Resource( SeedConst.ResourceId,$"{SeedConst.SystemResourceId},{SeedConst.ResourceId},",2 ) {
                ApplicationId = SeedConst.ApplicationId,
                ParentId = SeedConst.SystemResourceId,
                Name = "资源",
                I18n = "identity.resource",
                Icon = "apartment",
                PinYin = "zy",
                Uri = "/identity/resource",
                Type = ResourceType.Module,
                SortId = 3,
                Enabled = true,
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "881be306-9acc-4b8f-a638-1a43ed8b2f47"u8.ToArray()
            },
            new Resource( SeedConst.ModuleId,$"{SeedConst.SystemResourceId},{SeedConst.ResourceId},{SeedConst.ModuleId},",3 ) {
                ApplicationId = SeedConst.ApplicationId,
                ParentId = SeedConst.ResourceId,
                Name = "模块资源",
                PinYin = "mkzy",
                Type = ResourceType.Module,
                SortId = 1,
                IsHide = true,
                Enabled = true,
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "012C47E4-4612-4B6D-8A2D-0E6CB37BBF1F"u8.ToArray()
            },
            new Resource( SeedConst.OperationId,$"{SeedConst.SystemResourceId},{SeedConst.ResourceId},{SeedConst.OperationId},",3 ) {
                ApplicationId = SeedConst.ApplicationId,
                ParentId = SeedConst.ResourceId,
                Name = "操作资源",
                PinYin = "czzy",
                Type = ResourceType.Module,
                SortId = 2,
                IsHide = true,
                Enabled = true,
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "2BCAECC1-4D65-4BD7-8EB4-14C71E035CFA"u8.ToArray()
            },
            new Resource( SeedConst.ApiResourceId,$"{SeedConst.SystemResourceId},{SeedConst.ResourceId},{SeedConst.ApiResourceId},",3 ) {
                ApplicationId = SeedConst.ApplicationId,
                ParentId = SeedConst.ResourceId,
                Name = "Api资源",
                PinYin = "apizy",
                Type = ResourceType.Module,
                SortId = 3,
                IsHide = true,
                Enabled = true,
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "08A08C95-280E-48A4-A2A2-0490B371745C"u8.ToArray()
            },
            new Resource( SeedConst.IdentityResourceId,$"{SeedConst.SystemResourceId},{SeedConst.ResourceId},{SeedConst.IdentityResourceId},",3 ) {
                ApplicationId = SeedConst.ApplicationId,
                ParentId = SeedConst.ResourceId,
                Name = "身份资源",
                PinYin = "sfzy",
                Type = ResourceType.Module,
                SortId = 4,
                IsHide = true,
                Enabled = true,
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "4F329202-D411-4FF6-B45B-0511BCA794A3"u8.ToArray()
            },
            new Resource( SeedConst.CommonOperationId,$"{SeedConst.SystemResourceId},{SeedConst.ResourceId},{SeedConst.CommonOperationId},",3 ) {
                ApplicationId = SeedConst.ApplicationId,
                ParentId = SeedConst.ResourceId,
                Name = "常用操作管理",
                PinYin = "cyczgl",
                Type = ResourceType.Module,
                SortId = 9,
                IsHide = true,
                Enabled = true,
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "575A91A2-FA77-4B60-8663-01ED7627C10B"u8.ToArray()
            },
            new Resource( SeedConst.UserResourceId,$"{SeedConst.SystemResourceId},{SeedConst.UserResourceId},",2 ) {
                ApplicationId = SeedConst.ApplicationId,
                ParentId = SeedConst.SystemResourceId,
                Name = "用户",
                I18n = "identity.user",
                Icon = "user",
                PinYin = "yh",
                Uri = "/identity/user",
                Type = ResourceType.Module,
                SortId = 4,
                Enabled = true,
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "75d51762-d517-452f-bf46-67cf0de9cd26"u8.ToArray()
            },
            new Resource( SeedConst.RoleResourceId,$"{SeedConst.SystemResourceId},{SeedConst.RoleResourceId},",2 ) {
                ApplicationId = SeedConst.ApplicationId,
                ParentId = SeedConst.SystemResourceId,
                Name = "角色",
                I18n = "identity.role",
                Icon = "team",
                PinYin = "js",
                Uri = "/identity/role",
                Type = ResourceType.Module,
                SortId = 5,
                Enabled = true,
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "a4fa46b0-cad1-4862-9388-1bdd8efd607d"u8.ToArray()
            },
            new Resource( SeedConst.PermissionResourceId,$"{SeedConst.SystemResourceId},{SeedConst.PermissionResourceId},",2 ) {
                ApplicationId = SeedConst.ApplicationId,
                ParentId = SeedConst.SystemResourceId,
                Name = "权限",
                PinYin = "qx",
                Type = ResourceType.Module,
                SortId = 5,
                IsHide = true,
                Enabled = true,
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "C2B735A7-4B60-488D-9E6D-15EE62AFB911"u8.ToArray()
            },
            new Resource( SeedConst.OpenIdResourceId,$"{SeedConst.OpenIdResourceId},",1 ) {
                Name = "openid",
                Remark = "用户标识",
                Uri = "openid",
                Type = ResourceType.Identity,
                SortId = 1,
                Enabled = true,
                Claims = new List<string>{"sub"},
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "68792f77-4aaa-4ea0-a1a8-e5c940070910"u8.ToArray()
            },
            new Resource( SeedConst.ProfileResourceId,$"{SeedConst.ProfileResourceId},",1 ) {
                Name = "profile",
                Remark = "用户信息",
                Uri = "profile",
                Type = ResourceType.Identity,
                SortId = 1,
                Enabled = true,
                Claims = new List<string>{"profile","name"},
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "5fe23db5-7020-4596-9f16-c92525212993"u8.ToArray()
            },
            new Resource( SeedConst.ViewApplicationOperationId,null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "查看",
                Uri = "application.view",
                ParentId = SeedConst.AppliationResourceId,
                SortId = 1,
                Type = ResourceType.Operation,
                IsBase = true,
                Enabled = true,
                Remark = "查看应用程序",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "cba920f3-3c7a-4483-b991-b44f7a0e49f0"u8.ToArray()
            },
            new Resource( "A7C889B7-4F7E-416C-A4E7-6694E61C4ABD".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "创建",
                Uri = "application.create",
                ParentId = SeedConst.AppliationResourceId,
                SortId = 2,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "创建应用程序",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "dd9a3566-1be4-435e-b9d4-ce9d947a5053"u8.ToArray()
            },
            new Resource( "575A2E6E-6B3D-40EF-ABD0-A820BE29CC8F".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "更新",
                Uri = "application.update",
                ParentId = SeedConst.AppliationResourceId,
                SortId = 3,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "更新应用程序",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "3beb8876-e584-46d8-b9fb-5eb17c51d62c"u8.ToArray()
            },
            new Resource( "8F979359-A998-4C8E-83B7-B22815DAB9A8".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "删除",
                Uri = "application.delete",
                ParentId = SeedConst.AppliationResourceId,
                SortId = 4,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "删除应用程序",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "8faf0bbe-51d7-4e87-a431-989972f094c7"u8.ToArray()
            },
            new Resource( "8917E9E0-9E85-460E-88BA-704A697F6E3E".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "查看",
                Uri = "claim.view",
                ParentId = SeedConst.ClaimResourceId,
                SortId = 1,
                Type = ResourceType.Operation,
                IsBase = true,
                Enabled = true,
                Remark = "查看声明",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "8BA0D59A-CCC1-469C-8B15-A5867D4832B1"u8.ToArray()
            },
            new Resource( "24AFA389-0230-40B0-9795-CF38DB05AD18".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "创建",
                Uri = "claim.create",
                ParentId = SeedConst.ClaimResourceId,
                SortId = 2,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "创建声明",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "3465BC8F-DC86-46DA-BB97-1721E257143C"u8.ToArray()
            },
            new Resource( "914DC6FD-0C75-4AC0-821F-B7846BA15A0D".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "保存",
                Uri = "claim.save",
                ParentId = SeedConst.ClaimResourceId,
                SortId = 3,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "保存声明",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "A4C32FA8-F8EB-4CE9-A517-D96D431FCB04"u8.ToArray()
            },
            new Resource( "0088B0BD-6210-4E65-AE75-A642A5417809".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "删除",
                Uri = "claim.delete",
                ParentId = SeedConst.ClaimResourceId,
                SortId = 4,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "删除声明",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "EC9C35B4-3DFD-4CEE-BE70-9D83993B40E5"u8.ToArray()
            },
            new Resource( "A67D5D7E-8CEF-440D-8E7D-E7D2F4E3C321".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "查看",
                Uri = "module.view",
                ParentId = SeedConst.ModuleId,
                SortId = 1,
                Type = ResourceType.Operation,
                IsBase = true,
                Enabled = true,
                Remark = "查看模块资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "0D4498B9-8429-4467-B1AB-272C7A9638D6"u8.ToArray()
            },
            new Resource( "0B782400-52C0-413A-8BBB-CAFFE8E902B0".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "创建",
                Uri = "module.create",
                ParentId = SeedConst.ModuleId,
                SortId = 1,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "创建模块资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "E6A0F285-0C5F-4460-8DA5-5E65D22F5EBD"u8.ToArray()
            },
            new Resource( "1766B64D-1926-4D3B-9DA8-2DC7453DF41A".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "启用",
                Uri = "module.enable",
                ParentId = SeedConst.ModuleId,
                SortId = 1,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "启用模块资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "9DCAA203-3513-43F6-9892-023C22E6A191"u8.ToArray()
            },
            new Resource( "C84BDE6F-CE06-400C-91D9-38B4308914C8".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "禁用",
                Uri = "module.disable",
                ParentId = SeedConst.ModuleId,
                SortId = 1,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "禁用模块资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "012C47E4-4612-4B6D-8A2D-0E6CB37BBF1F"u8.ToArray()
            },
            new Resource( "D2A61FF2-B713-41A8-A5EE-F9349B49AA21".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "更新",
                Uri = "module.update",
                ParentId = SeedConst.ModuleId,
                SortId = 1,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "更新模块资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "2BCAECC1-4D65-4BD7-8EB4-14C71E035CFA"u8.ToArray()
            },
            new Resource( "2033D9F9-E836-4767-A710-AD7E589F4DA9".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "删除",
                Uri = "module.delete",
                ParentId = SeedConst.ModuleId,
                SortId = 1,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "删除模块资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "BED1CE22-7EC8-44EB-B646-1A9846B3C622"u8.ToArray()
            },
            new Resource( "F29522BA-EF0B-488F-B4F3-49A8DFE7042E".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "资源设置",
                Uri = "module.settings",
                ParentId = SeedConst.ModuleId,
                SortId = 1,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "模块资源设置",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "04E13F8A-3546-48D9-8DF5-2D73A49CC58E"u8.ToArray()
            },
            new Resource( "4A0B65E8-7145-48C4-A400-18934A90EBF7".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "查看",
                Uri = "operation.view",
                ParentId = SeedConst.OperationId,
                SortId = 1,
                Type = ResourceType.Operation,
                IsBase = true,
                Enabled = true,
                Remark = "查看操作资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "87A3C77D-00B8-45E9-886D-012980A7549C"u8.ToArray()
            },
            new Resource( "95031849-2DA1-464B-948E-8218415E641F".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "创建",
                Uri = "operation.create",
                ParentId = SeedConst.OperationId,
                SortId = 2,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "创建操作资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "F2A94B5A-E46A-4B42-BF6E-0153EEA9DE28"u8.ToArray()
            },
            new Resource( "7F15A965-387D-43AB-951E-D23B07BD1675".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "更新",
                Uri = "operation.update",
                ParentId = SeedConst.OperationId,
                SortId = 3,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "更新操作资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "A525A1C3-E99C-47F3-8D95-01639DF3C45C"u8.ToArray()
            },
            new Resource( "9D9BA908-80C7-48AD-8EE9-F43772F7C738".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "删除",
                Uri = "operation.delete",
                ParentId = SeedConst.OperationId,
                SortId = 4,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "删除操作资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "CFFCE775-0C78-4078-892C-016444C0F163"u8.ToArray()
            },
            new Resource( "09A52BD1-997C-483A-9026-01F306E2CC84".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "查看",
                Uri = "commonOperation.view",
                ParentId = SeedConst.CommonOperationId,
                SortId = 1,
                Type = ResourceType.Operation,
                IsBase = true,
                Enabled = true,
                Remark = "查看常用操作",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "015A48C3-443C-4E2F-9232-01F44D77BEF6"u8.ToArray()
            },
            new Resource( "376F621F-BAB1-4EC2-A688-01FE1877E842".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "创建",
                Uri = "commonOperation.create",
                ParentId = SeedConst.CommonOperationId,
                SortId = 2,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "创建常用操作",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "C22A3B3A-2EC2-4727-811F-02074AD40A37"u8.ToArray()
            },
            new Resource( "4A672A64-EDE1-4356-B19B-020FE1D713C6".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "保存",
                Uri = "commonOperation.save",
                ParentId = SeedConst.CommonOperationId,
                SortId = 3,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "保存常用操作",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "07E983D9-2A0B-406B-9263-021B7D556B4E"u8.ToArray()
            },
            new Resource( "3511C3F2-D444-4F20-8C48-023E9D1AEC3A".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "删除",
                Uri = "commonOperation.delete",
                ParentId = SeedConst.CommonOperationId,
                SortId = 4,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "删除常用操作",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "D4544759-461C-4803-ABCF-025DF400B9D5"u8.ToArray()
            },
            new Resource( "C389755D-2F53-4F79-AD4E-01841CA12BAD".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "查看",
                Uri = "apiResource.view",
                ParentId = SeedConst.ApiResourceId,
                SortId = 1,
                Type = ResourceType.Operation,
                IsBase = true,
                Enabled = true,
                Remark = "查看Api资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "EDA2C4C8-7C01-499D-B177-0CBED3B05862"u8.ToArray()
            },
            new Resource( "1BB3DA10-8DE0-48D0-B48C-0CC5D9110575".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "创建",
                Uri = "apiResource.create",
                ParentId = SeedConst.ApiResourceId,
                SortId = 2,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "创建Api资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "B390FC5B-8600-40AB-A997-0CE3BA7AD922"u8.ToArray()
            },
            new Resource( "4BB75118-6395-4DB4-A031-0CE63BA1FFF7".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "更新",
                Uri = "apiResource.update",
                ParentId = SeedConst.ApiResourceId,
                SortId = 3,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "更新Api资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "49732A46-62FE-40D2-AB63-0D44857AD57C"u8.ToArray()
            },
            new Resource( "22029026-DE32-483C-BE42-0D67C8313195".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "启用",
                Uri = "apiResource.enable",
                ParentId = SeedConst.ApiResourceId,
                SortId = 4,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "启用Api资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "3189E90A-D192-4AC3-BA61-0D69C5C6CE06"u8.ToArray()
            },
            new Resource( "972B89F8-2C28-45CD-AD4D-0D7E22BCAA13".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "禁用",
                Uri = "apiResource.disable",
                ParentId = SeedConst.ApiResourceId,
                SortId = 5,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "禁用Api资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "07429598-82DD-485C-A9E1-0DAF642F1CE5"u8.ToArray()
            },
            new Resource( "8A22A16A-10D6-4886-A8F9-0DE2DFF88A9A".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "删除",
                Uri = "apiResource.delete",
                ParentId = SeedConst.ApiResourceId,
                SortId = 6,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "删除Api资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "F9DA5B33-9DAB-464E-8A13-0DE4883B8EA6"u8.ToArray()
            },
            new Resource( "93742F2A-A27B-44F9-8E43-0DFAE065CEFA".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "查看",
                Uri = "identityResource.view",
                ParentId = SeedConst.IdentityResourceId,
                SortId = 1,
                Type = ResourceType.Operation,
                IsBase = true,
                Enabled = true,
                Remark = "查看身份资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "802ABD31-EBD5-4DAF-BB08-0E240C88957D"u8.ToArray()
            },
            new Resource( "DA5EBCA9-F2E1-4CF8-93A6-0E48DCB0C461".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "创建",
                Uri = "identityResource.create",
                ParentId = SeedConst.IdentityResourceId,
                SortId = 2,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "创建身份资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "D35164A1-6733-4177-AEFD-0E4F6A350118"u8.ToArray()
            },
            new Resource( "CCB020F6-C756-4183-A180-0E8ED9EC5170".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "更新",
                Uri = "identityResource.update",
                ParentId = SeedConst.IdentityResourceId,
                SortId = 3,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "更新身份资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "37C32095-6B0E-4440-8D04-0EA93CD1FA6F"u8.ToArray()
            },
            new Resource( "9D68775E-1EBF-48E6-B668-0EF97F054068".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "删除",
                Uri = "identityResource.delete",
                ParentId = SeedConst.IdentityResourceId,
                SortId = 4,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "删除身份资源",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "764A0D1D-7E3F-49C0-9F77-0F19B5D4DDBA"u8.ToArray()
            },
            new Resource( "2F60A136-5E31-43D9-81E7-104993080280".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "查看",
                Uri = "user.view",
                ParentId = SeedConst.UserResourceId,
                SortId = 1,
                Type = ResourceType.Operation,
                IsBase = true,
                Enabled = true,
                Remark = "查看用户",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "03981071-256C-4758-B9A2-105E8E030CC3"u8.ToArray()
            },
            new Resource( "FFD031B3-9091-4D6A-B913-10677EE96B39".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "创建",
                Uri = "user.create",
                ParentId = SeedConst.UserResourceId,
                SortId = 2,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "创建用户",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "62BFB0F0-D808-4A58-9D87-106A5A2B967C"u8.ToArray()
            },
            new Resource( "C003A8EA-FC54-446F-B6BD-106E50AD0470".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "删除",
                Uri = "user.delete",
                ParentId = SeedConst.UserResourceId,
                SortId = 3,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "删除用户",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "106D6FCE-38BB-47FC-A808-109D4ABE0F23"u8.ToArray()
            },
            new Resource( "5B47784D-AE87-44FE-A5B5-113003324BBF".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "查看",
                Uri = "role.view",
                ParentId = SeedConst.RoleResourceId,
                SortId = 1,
                Type = ResourceType.Operation,
                IsBase = true,
                Enabled = true,
                Remark = "查看角色",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "9BC6265E-6DD4-4A0F-9968-11563CD464ED"u8.ToArray()
            },
            new Resource( "545DB6BB-D65A-4CA1-9BED-1174F40F4271".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "创建",
                Uri = "role.create",
                ParentId = SeedConst.RoleResourceId,
                SortId = 2,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "创建角色",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "455BDF65-73CF-45A3-9A83-118A33CD8AA0"u8.ToArray()
            },
            new Resource( "DC125BEA-29D8-448D-BBD1-119928D02BC5".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "更新",
                Uri = "role.update",
                ParentId = SeedConst.RoleResourceId,
                SortId = 3,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "更新角色",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "3D435320-BF8A-47F8-BC93-11BDC22286F2"u8.ToArray()
            },
            new Resource( "F9431293-3758-4737-9030-11EA5F8EEC35".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "删除",
                Uri = "role.delete",
                ParentId = SeedConst.RoleResourceId,
                SortId = 4,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "删除角色",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "ED793A87-D1E7-49FB-BF69-121D11D062BF"u8.ToArray()
            },
            new Resource( "C25A16B1-CECE-46B3-8414-12A8491AFB06".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "用户设置",
                Uri = "role.userSettings",
                ParentId = SeedConst.RoleResourceId,
                SortId = 5,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "角色用户设置",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "15EC5D2F-828A-4DBB-9F68-12AA8246FF8F"u8.ToArray()
            },
            new Resource( "DE8B4989-5568-47A1-BC3B-12B7C0B54784".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "权限设置",
                Uri = "permission.view",
                ParentId = SeedConst.PermissionResourceId,
                SortId = 1,
                Type = ResourceType.Operation,
                IsBase = true,
                Enabled = true,
                Remark = "权限设置",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "FC71E793-C6C6-471B-A320-130DE7C9A683"u8.ToArray()
            },
            new Resource( "414D9BB9-ACA4-4496-9FFC-15F917E2D3D5".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "授予操作权限",
                Uri = "permission.grantOperation",
                ParentId = SeedConst.PermissionResourceId,
                SortId = 2,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "授予操作权限",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "3A7079BD-CB9B-4ABB-8B44-15FDADE5C315"u8.ToArray()
            },
            new Resource( "B84E8744-8A93-45A6-9DC4-16438631E1B1".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "拒绝操作权限",
                Uri = "permission.denyOperation",
                ParentId = SeedConst.PermissionResourceId,
                SortId = 3,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "拒绝操作权限",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "870907D4-2CC2-4471-8BCB-164980016330"u8.ToArray()
            },
            new Resource( "637534D1-0B4F-4DDE-8B8F-16766BDDC7F7".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "授予Api权限",
                Uri = "permission.grantApi",
                ParentId = SeedConst.PermissionResourceId,
                SortId = 4,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "授予Api权限",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "9D1F32C4-5363-4DF0-A750-1687F143C29C"u8.ToArray()
            },
            new Resource( "4EBF8AEB-130A-40DE-A098-16D138E6638D".ToGuid(),null,0 ) {
                ApplicationId = SeedConst.ApplicationId,
                Name = "拒绝Api权限",
                Uri = "permission.denyApi",
                ParentId = SeedConst.PermissionResourceId,
                SortId = 5,
                Type = ResourceType.Operation,
                Enabled = true,
                Remark = "拒绝Api权限",
                CreationTime = DateTime.UtcNow,
                LastModificationTime = DateTime.UtcNow,
                CreatorId = SeedConst.UserId,
                LastModifierId = SeedConst.UserId,
                Version = "6DEFD95E-433A-4212-A95D-16E2DACE63BB"u8.ToArray()
            },
        };
    }
}