apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency-pubsub
spec:
  policies:
    retries:
      pubsubRetry:
        policy: constant
        duration: 3s
        maxRetries: 3
  targets:
    components:
      pubsub:
        inbound:
          retry: pubsubRetry